"""empty message

Revision ID: 85574b4ff618
Revises: f56dd43d894d
Create Date: 2017-09-24 11:19:43.268720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85574b4ff618'
down_revision = 'f56dd43d894d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'changed_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('changed_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
